# Generated by Django 4.1.3 on 2022-11-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pecho_declinado',
            name='repeticiones',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pecho_declinado',
            name='series',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pecho_inclinado',
            name='repeticiones',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pecho_inclinado',
            name='series',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pecho_plano',
            name='repeticiones',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pecho_plano',
            name='series',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pecho_plano',
            name='maquina',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pecho_plano',
            name='peso',
            field=models.IntegerField(blank=True),
        ),
    ]
