# Generated by Django 4.1.3 on 2022-11-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_pecho_declinado_maquina_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pecho_inclinado',
            new_name='espalda',
        ),
        migrations.RenameModel(
            old_name='pecho_declinado',
            new_name='pecho',
        ),
        migrations.RenameModel(
            old_name='pecho_plano',
            new_name='piernas',
        ),
    ]
